// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVaGLFZuz-bIBzXvr9ksL2NK6OvKmC5JM',
    appId: '1:170166474875:web:15ad7f606be337924aeade',
    messagingSenderId: '170166474875',
    projectId: 'arena-a99f8',
    authDomain: 'arena-a99f8.firebaseapp.com',
    storageBucket: 'arena-a99f8.firebasestorage.app',
    measurementId: 'G-5ZB3QX32L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7gQxB7jB03CQylV3fwlgdlhkOjwJys7A',
    appId: '1:170166474875:android:324e6ac3f350449f4aeade',
    messagingSenderId: '170166474875',
    projectId: 'arena-a99f8',
    storageBucket: 'arena-a99f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlyZk1fFGxN8jZ6JifPp6iw4PyWC1NBo8',
    appId: '1:170166474875:ios:17dfdb5d74dbb9f54aeade',
    messagingSenderId: '170166474875',
    projectId: 'arena-a99f8',
    storageBucket: 'arena-a99f8.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlyZk1fFGxN8jZ6JifPp6iw4PyWC1NBo8',
    appId: '1:170166474875:ios:17dfdb5d74dbb9f54aeade',
    messagingSenderId: '170166474875',
    projectId: 'arena-a99f8',
    storageBucket: 'arena-a99f8.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVaGLFZuz-bIBzXvr9ksL2NK6OvKmC5JM',
    appId: '1:170166474875:web:5e0d457a367334644aeade',
    messagingSenderId: '170166474875',
    projectId: 'arena-a99f8',
    authDomain: 'arena-a99f8.firebaseapp.com',
    storageBucket: 'arena-a99f8.firebasestorage.app',
    measurementId: 'G-9ZBETRKH4S',
  );
}
